with open('static/app.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the AI generation function system prompt and replace it
old_sys = '''  const systemPrompt = `You are an expert at designing AI agent personas. Given a role name and any context, return a JSON object that fully populates an agent profile. Return ONLY valid JSON, no markdown fences, no preamble.

Schema (all fields are strings unless noted):
{
  "tone": "communication tone/style",
  "expertise": "areas of expertise",
  "goal": "primary objective — what the agent is built to do",
  "outcome": "what success looks like (one sentence)",
  "audience": "target audience",
  "domain": "industry or domain",
  "tasks": "2-3 sentence description of primary tasks",
  "output_format": "how responses should be structured",
  "constraints": "what NOT to do (2-3 rules)",
  "opening_message": "what the agent says when first activated",
  "persona": "rich first-person persona paragraph (3-4 sentences)",
  "response_style": "one of: formal, casual, direct, detailed, concise, persuasive, educational, empathetic",
  "depth": "one of: quick, balanced, deep_dive, adaptive",
  "format_mode": "one of: prose, bullets, numbered, headers, code_blocks",
  "interaction_mode": "one of: reactive, proactive, clarify_first, auto_proceed",
  "flags": ["array of any: no_hedging, cite_sources, ask_clarify, step_by_step, no_preamble, show_reasoning, use_examples, stay_on_topic, structured_output, no_repetition"]
}`;'''

new_sys = '''  const systemPrompt = `You are an expert at designing AI agent personas. Given a role name and context, return a JSON object that FULLY populates every field of a richly detailed agent profile. Make it specific, opinionated, and impressive — this is what the user will show off. Return ONLY valid JSON, no markdown fences, no preamble.

Schema (all fields required — make each one detailed and specific to the role):
{
  "tone": "specific communication tone — e.g. Forensic and impatient. No softening. Asks the question no one wants asked.",
  "expertise": "comma-separated expertise areas — specific, not generic",
  "goal": "one sharp sentence — what this agent exists to do",
  "outcome": "one sentence — what success concretely looks like",
  "audience": "specific target user — job title, context, pain point",
  "domain": "industry or domain",
  "tasks": "3-4 specific tasks this agent handles — be concrete, name real deliverables",
  "output_format": "exactly how outputs are structured — e.g. Lead with the answer. Three supporting points. One action to take.",
  "constraints": "3 sharp rules for what NOT to do — specific, not generic",
  "opening_message": "exactly what this agent says when first activated — first-person, specific to the role",
  "persona": "rich 4-5 sentence first-person persona paragraph — voice, background, philosophy, how they think",
  "persistent_context": "2-3 facts this agent always carries — e.g. Assumes B2B audience. Always uses active voice. Never recommends more than 3 options.",
  "response_style": "one of: formal, casual, direct, detailed, concise, persuasive, educational, empathetic",
  "depth": "one of: quick, balanced, deep_dive, adaptive",
  "format_mode": "one of: prose, bullets, numbered, headers, code_blocks",
  "interaction_mode": "one of: reactive, proactive, clarify_first, auto_proceed",
  "flags": ["choose 4-6 from: no_hedging, cite_sources, ask_clarify, step_by_step, no_preamble, show_reasoning, use_examples, stay_on_topic, structured_output, no_repetition"],
  "skills": [
    {
      "name": "Skill name — e.g. Cold Email Architecture",
      "description": "What this skill does and why it matters for this agent — 1-2 sentences",
      "example": "One specific example sentence showing the skill in action — as if the agent is doing it"
    }
  ],
  "knowledge_base": [
    {
      "name": "Entry name — e.g. Brand Voice Rules",
      "when_to_use": "Specific trigger — e.g. Writing any client-facing copy or taglines",
      "content": "The actual knowledge — 2-4 concrete rules, facts, or principles this agent references",
      "include": true
    }
  ],
  "example_phrases": [
    { "text": "A phrase that shows exactly how this agent talks — make it memorable and specific to the voice" },
    { "text": "A second distinct phrase — different register or use case" },
    { "text": "A third phrase — could be a question this agent asks or a signature way of framing" }
  ]
}

Generate 3-5 skills, 2-4 knowledge base entries, and 3-5 example phrases. Make them rich, specific, and immediately usable. This should read like the agent was designed by an expert, not generated by a template.`;'''

assert old_sys in content, "SYSTEM PROMPT NOT FOUND"
content = content.replace(old_sys, new_sys)
print("System prompt updated")

# Now fix the response handler to use .on (not .active) and render skills/KB/examples
old_activate = '''    const activateChip = (groupId, val) => {
      if (!val) return;
      $$(`${groupId} .role-chip`).forEach(c => c.classList.toggle('active', c.dataset.val === val));
      const hidden = $(`${groupId}`).closest('.form-group')?.querySelector('input[type=hidden]');
      if (hidden) hidden.value = val;
    };
    activateChip('#roleStyleChips',      d.response_style);
    activateChip('#roleDepthChips',      d.depth);
    activateChip('#roleFormatModeChips', d.format_mode);
    activateChip('#roleProcTypeChips',   d.interaction_mode);

    if (Array.isArray(d.flags) && d.flags.length) {
      $$('#roleFlagChips .role-chip').forEach(c => c.classList.toggle('active', d.flags.includes(c.dataset.val)));
      const flagHidden = $('#roleFlagsInput');
      if (flagHidden) flagHidden.value = d.flags.join(',');
    }

    updateRolePromptPreview();
    toast('Agent generated — review and save', 'success');'''

new_activate = '''    // Activate chip groups using .on class (consistent with rest of system)
    const activateChip = (groupId, val) => {
      if (!val) return;
      const v = val.toLowerCase();
      $$(groupId + ' .role-chip').forEach(c => {
        c.classList.toggle('on', c.dataset.val === v);
      });
    };
    activateChip('#roleStyleChips',      d.response_style);
    activateChip('#roleDepthChips',      d.depth);
    activateChip('#roleFormatModeChips', d.format_mode);
    activateChip('#roleProcTypeChips',   d.interaction_mode);

    if (Array.isArray(d.flags) && d.flags.length) {
      $$('#roleFlagChips .role-chip').forEach(c => c.classList.toggle('on', d.flags.includes(c.dataset.val)));
    }

    // Render skills, KB, example phrases
    if (Array.isArray(d.skills) && d.skills.length) renderSkillList(d.skills);
    if (Array.isArray(d.knowledge_base) && d.knowledge_base.length) renderKbList(d.knowledge_base);
    if (Array.isArray(d.example_phrases) && d.example_phrases.length) renderExampleList(d.example_phrases);

    // Set persistent_context field
    const pcEl = $('#roleMemoryInput');
    if (pcEl && d.persistent_context) pcEl.value = d.persistent_context;

    updateRolePromptPreview();
    toast('Agent generated — review and save', 'success');'''

assert old_activate in content, "ACTIVATE BLOCK NOT FOUND"
content = content.replace(old_activate, new_activate)
print("AI response handler updated")

# Also increase max_tokens since we now generate much more content
content = content.replace(
    "body: JSON.stringify({ model: 'gpt-4o-mini', messages: [{ role: 'system', content: systemPrompt }, { role: 'user', content: userMsg }], max_tokens: 900 }),",
    "body: JSON.stringify({ model: 'gpt-4o-mini', messages: [{ role: 'system', content: systemPrompt }, { role: 'user', content: userMsg }], max_tokens: 2000 }),"
)
content = content.replace(
    "body: JSON.stringify({ model: 'claude-haiku-4-5-20251001', system: systemPrompt, messages: [{ role: 'user', content: userMsg }], max_tokens: 900 }),",
    "body: JSON.stringify({ model: 'claude-haiku-4-5-20251001', system: systemPrompt, messages: [{ role: 'user', content: userMsg }], max_tokens: 2000 }),"
)
content = content.replace(
    "body: JSON.stringify({ contents: [{ parts: [{ text: systemPrompt + '\\n\\n' + userMsg }] }] }),",
    "body: JSON.stringify({ contents: [{ parts: [{ text: systemPrompt + '\\n\\n' + userMsg }] }], generationConfig: { maxOutputTokens: 2000 } }),"
)
# OpenRouter max_tokens
import re
content = re.sub(
    r"(model, messages: \[.*?\], max_tokens: )900(\})",
    r"\g<1>2000\2",
    content
)
print("max_tokens updated")

with open('static/app.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("AI generation fixes done")
