import os
os.chdir(r'C:\Users\Eugene Phillips\Desktop\Prompt Library Update')

code = open('static/app.js', 'r', encoding='utf-8').read()

pcw_start = code.index('(function initComponentsWorkspace()')

# ── 1. Add new categories ──────────────────────────────────────────────────

OLD_CATS_END = "    { id: 'personas',   label: 'Personas & Identity',    icon: 'face',              color: '#ec4899'         },\n  ];"
NEW_CATS_END = """    { id: 'personas',   label: 'Personas & Identity',    icon: 'face',              color: '#ec4899'         },
    { id: 'prompteng',  label: 'Prompt Engineering',     icon: 'engineering',       color: '#eab308'         },
    { id: 'usecases',   label: 'Use Case Library',        icon: 'lightbulb',         color: '#06b6d4'         },
  ];"""

assert OLD_CATS_END in code[pcw_start:], "cats end not found"
code = code.replace(OLD_CATS_END, NEW_CATS_END, 1)

# ── 2. Build new blocks string ─────────────────────────────────────────────

NEW_BLOCKS = """
    // ── CONTROL FLOW (additional) ────────────────────────────────────────────
    { cat: 'control', icon: 'call_split',       label: 'Conditional Branch',    text: 'IF [condition is true]:\\n  THEN [action A]\\nELSE IF [alternative condition]:\\n  THEN [action B]\\nELSE:\\n  [default action]\\n\\nApply this logic to: [task or decision]' },
    { cat: 'control', icon: 'swap_horiz',       label: 'Switch-Case Dispatcher', text: 'Based on the value of [input variable], do the following:\\n\\nCASE [value 1]: [action 1]\\nCASE [value 2]: [action 2]\\nCASE [value 3]: [action 3]\\nCASE [value 4]: [action 4]\\nDEFAULT: [fallback action if no case matches]' },
    { cat: 'control', icon: 'loop',             label: 'Loop Until Condition',   text: 'Repeat the following process:\\n\\nAction: [what to do each iteration]\\nInput: [what changes each loop]\\nCheck: [condition that must be true to stop]\\nMax iterations: [N — hard stop regardless of condition]\\nOn completion: [what to do with the final output]' },
    { cat: 'control', icon: 'exit_to_app',      label: 'Early Exit Gate',        text: 'Before proceeding, check the following exit conditions:\\n\\nExit if: [condition 1 — e.g. input is empty or invalid]\\nExit if: [condition 2 — e.g. task is already complete]\\nExit if: [condition 3 — e.g. required information is missing]\\n\\nIf an exit condition is met: [what to return or do instead]\\nIf all clear: proceed with [main task]' },
    { cat: 'control', icon: 'refresh',          label: 'Retry with Backoff',     text: 'Attempt the following task up to [N] times:\\n\\nTask: [what to attempt]\\nRetry condition: [what error or failure triggers a retry]\\nBackoff: wait [X] seconds between attempts (increase by [multiplier] each retry)\\nMax retries: [N]\\nOn final failure: [what to do if all attempts fail]' },
    { cat: 'control', icon: 'alt_route',        label: 'Fallback Chain',         text: 'Try the following options in order. Move to the next only if the previous fails or returns insufficient output.\\n\\nOption 1 (preferred): [primary approach]\\nOption 2 (fallback): [secondary approach]\\nOption 3 (last resort): [minimal viable approach]\\nIf all fail: [what to return or report]' },
    { cat: 'control', icon: 'account_tree',     label: 'Parallel Tasks',         text: 'Execute the following tasks simultaneously (they do not depend on each other):\\n\\nTask A: [task A description]\\nTask B: [task B description]\\nTask C: [task C description]\\n\\nSync point: [what to do when all tasks complete]\\nOutput: [how to combine the results]' },
    { cat: 'control', icon: 'linear_scale',     label: 'Sequential Pipeline',    text: 'Execute these steps in strict order. Each step feeds into the next.\\n\\nStep 1 — [name]: [instruction] → Output: [what this produces]\\nStep 2 — [name]: [instruction, using Step 1 output] → Output: [what this produces]\\nStep 3 — [name]: [instruction, using Step 2 output] → Output: [final result]\\n\\nDo not start Step N+1 until Step N is complete.' },
    { cat: 'control', icon: 'device_hub',       label: 'State Machine',          text: 'MODEL THIS AS A STATE MACHINE:\\n\\nInitial state: [starting state]\\nStates: [state A], [state B], [state C], [state D]\\n\\nTransitions:\\n[state A] --[trigger]--> [state B]\\n[state B] --[trigger]--> [state C]\\n[state C] --[trigger]--> [state A] or [state D]\\n\\nTerminal states: [states where the machine stops]\\nCurrent input: [what to process]' },
    { cat: 'control', icon: 'electric_bolt',    label: 'Circuit Breaker',        text: 'CIRCUIT BREAKER PATTERN:\\n\\nMonitor: [what to watch — e.g. error rate, latency, failure count]\\nThreshold: trip if [condition — e.g. 3 failures in 60 seconds]\\n\\nStates:\\n- CLOSED (normal): process requests normally\\n- OPEN (tripped): reject requests immediately, return [fallback response]\\n- HALF-OPEN (testing): allow 1 request through to test recovery\\n\\nReset after: [time or condition]' },
    { cat: 'control', icon: 'timer',            label: 'Timeout Handler',        text: 'Execute the following with a time budget:\\n\\nTask: [what to do]\\nTimeout: [N] seconds\\nProgress check: every [interval] seconds, verify [checkpoint condition]\\n\\nOn timeout: [what to return — partial result / error / fallback]\\nOn success: [what to do with the completed output]' },
    { cat: 'control', icon: 'low_priority',     label: 'Priority Router',        text: 'Route the input to the appropriate handler based on priority:\\n\\nCRITICAL (P0): [condition] → [handler / action]\\nHIGH (P1):     [condition] → [handler / action]\\nMEDIUM (P2):   [condition] → [handler / action]\\nLOW (P3):      [condition] → [handler / action]\\n\\nInput to route: [describe it]\\nTiebreaker: [if multiple priorities match, prefer the highest]' },

    // ── GUARDRAILS (additional) ────────────────────────────────────────────────
    { cat: 'guardrails', icon: 'rule',          label: 'Output Validator',       text: 'Before returning your response, validate it against these rules:\\n\\n[ ] The output matches the requested format exactly\\n[ ] All required sections are present\\n[ ] No prohibited content is included (see: [list])\\n[ ] Claims are supported by the information provided\\n[ ] Length is within [min]–[max] [words/tokens/lines]\\n\\nIf any check fails: rewrite the output until it passes all checks.' },
    { cat: 'guardrails', icon: 'format_shapes', label: 'Format Enforcer',        text: 'STRICT FORMAT RULE:\\nYour response MUST follow this exact structure:\\n\\n[Section 1 name]: [description of what goes here]\\n[Section 2 name]: [description]\\n[Section 3 name]: [description]\\n\\nDo NOT:\\n- Add sections not listed above\\n- Omit any listed section\\n- Use a different order\\n- Add preamble or commentary outside the structure\\n\\nIf you cannot fill a section, write "N/A — [reason]" rather than skipping it.' },
    { cat: 'guardrails', icon: 'straighten',    label: 'Length Guard',           text: 'RESPONSE LENGTH CONSTRAINT:\\n\\nMaximum: [N] [words / sentences / bullet points / lines]\\nMinimum: [M] [words / sentences / bullet points / lines]\\n\\nDo not pad output to meet the minimum. Do not truncate important information to meet the maximum. If you cannot complete the task within the limit, say so and ask for clarification.\\n\\nTarget length: [N] [unit]' },
    { cat: 'guardrails', icon: 'link',          label: 'Citation Required',      text: 'Every factual claim in your response must be followed by a source indicator.\\n\\nFormat: "[claim] [Source: type]"\\n\\nSource types:\\n- [Document]: cite as (Doc: [title], p. [N])\\n- [Knowledge]: flag as (General knowledge — not verified)\\n- [Inference]: flag as (Inference — not stated explicitly)\\n- [Unknown]: flag as (Source unknown — verify before using)\\n\\nIf a claim has no source, flag it explicitly rather than stating it as fact.' },
    { cat: 'guardrails', icon: 'percent',       label: 'Confidence Threshold',   text: 'For every claim or recommendation, assign a confidence level:\\n\\nHIGH (>85%): state as fact\\nMEDIUM (50–85%): flag with "likely" or "probably"\\nLOW (<50%): flag with "uncertain" or "I am not sure"\\nUNKNOWN: state explicitly "I do not have enough information to say"\\n\\nDo not present low-confidence claims as high-confidence ones. When uncertain, say so before giving the answer.' },
    { cat: 'guardrails', icon: 'privacy_tip',   label: 'PII Scrubber',           text: 'Before returning any output, scan for and remove or mask personally identifiable information (PII).\\n\\nPII to detect and mask:\\n- Full names → [PERSON]\\n- Email addresses → [EMAIL]\\n- Phone numbers → [PHONE]\\n- Physical addresses → [ADDRESS]\\n- National ID / passport numbers → [ID]\\n- Financial account numbers → [ACCOUNT]\\n- Dates of birth → [DOB]\\n\\nIf removing PII breaks the meaning of the output, flag it: "PII removed — context may be incomplete."' },
    { cat: 'guardrails', icon: 'security',      label: 'Red Team Block',         text: 'Before finalising this output, perform a red-team check:\\n\\n1. If a bad actor read this, could they misuse it? [yes/no/how]\\n2. Does it reveal sensitive information about [subject]? [yes/no]\\n3. Could it be used to cause harm to [protected group]? [yes/no]\\n4. Does it make claims that could be legally problematic? [yes/no]\\n5. Is it compliant with [policy/regulation]? [yes/no]\\n\\nIf any answer is "yes": revise before returning.' },
    { cat: 'guardrails', icon: 'troubleshoot',  label: 'Adversarial Test',       text: 'Test whether this prompt or output is robust against adversarial inputs:\\n\\nTest 1 — Empty input: what happens if the user provides nothing?\\nTest 2 — Irrelevant input: what if the user provides off-topic content?\\nTest 3 — Prompt injection: what if input tries to override instructions?\\nTest 4 — Edge values: what if input is unusually long, short, or formatted?\\nTest 5 — Contradiction: what if input contradicts the system prompt?\\n\\nFor each failure: describe what breaks and the fix.' },
    { cat: 'guardrails', icon: 'compare_arrows', label: 'Self-Consistency Check', text: 'After generating your response, check it for internal consistency:\\n\\n[ ] Does the conclusion follow from the evidence presented?\\n[ ] Are all recommendations consistent with each other?\\n[ ] Are any claims contradicted elsewhere in the response?\\n[ ] Does the tone remain consistent throughout?\\n[ ] Do the examples support the principle they are meant to illustrate?\\n\\nIf you find an inconsistency: rewrite before returning.' },
    { cat: 'guardrails', icon: 'not_interested', label: 'No-Fabrication Rule',   text: 'ANTI-FABRICATION RULE — applies to this entire response:\\n\\nDo NOT invent or fabricate:\\n- Statistics or data points\\n- Citations, references, or studies\\n- Names of people, organisations, or products\\n- Dates or events\\n- Quotes\\n\\nIf you do not know a fact with confidence, use one of these instead:\\n- "I do not have data on this"\\n- "You should verify this independently"\\n- "[Placeholder — insert real figure here]"\\n\\nBetter to be incomplete than to be confidently wrong.' },
    { cat: 'guardrails', icon: 'warning',        label: 'Escalation Trigger',    text: 'ESCALATION CONDITIONS:\\n\\nEscalate immediately (do not proceed) if any of the following are true:\\n- [Condition 1 — e.g. request involves harm to a person]\\n- [Condition 2 — e.g. request is outside authorised scope]\\n- [Condition 3 — e.g. required data is missing or corrupt]\\n- [Condition 4 — e.g. confidence in output is below threshold]\\n\\nEscalation action: [what to do — e.g. return error, notify human, request clarification]\\nDo not attempt to complete the task before escalating.' },
    { cat: 'guardrails', icon: 'difference',     label: 'Contradiction Detector', text: 'Review the following input/output for contradictions:\\n\\nContent to check:\\n[paste content here]\\n\\nLook for:\\n1. Direct contradictions (A says X, B says not-X)\\n2. Implicit contradictions (A implies X, B implies not-X)\\n3. Scope creep (claims that exceed what the evidence supports)\\n4. False equivalences (comparing unlike things as equal)\\n\\nFor each found: quote both sides, explain the contradiction, and suggest a resolution.' },

    // ── PERSONAS & IDENTITY (additional) ─────────────────────────────────────
    { cat: 'personas', icon: 'school',          label: 'Socratic Tutor',         text: 'You are a Socratic tutor. You never give direct answers. Instead, you guide the learner to discover answers through carefully sequenced questions.\\n\\nYour approach:\\n- Ask one question at a time\\n- Start from what the learner already knows\\n- Use their answers to form the next question\\n- When they reach a wrong assumption, ask them to examine it\\n- Celebrate reasoning, not just correct answers\\n\\nNever say: "The answer is X." Instead: "What do you think would happen if...?"' },
    { cat: 'personas', icon: 'psychology_alt',  label: "Devil's Advocate",       text: "You are a devil's advocate. Your role is to challenge every position, find every flaw, and stress-test every assumption — not to be destructive, but to make the final decision stronger.\\n\\nYour rules:\\n- Find the strongest possible objection to every claim\\n- Identify assumptions that have not been tested\\n- Ask: what could go wrong? Who disagrees and why?\\n- Do not concede easily — push back until the argument can withstand scrutiny\\n- End with: the three weakest points in the current position" },
    { cat: 'personas', icon: 'rubber_stamp',    label: 'Rubber Duck Debugger',   text: 'You are a rubber duck debugger — a patient, non-judgemental listener who helps people think through problems by asking them to explain their thinking step by step.\\n\\nYour approach:\\n- Ask the person to walk you through the problem from the beginning\\n- Ask clarifying questions when something is assumed or skipped\\n- Reflect back what they have said to confirm your understanding\\n- Ask: "And what did you expect to happen at that step?"\\n- You do not solve — you prompt. The person solves it themselves.' },
    { cat: 'personas', icon: 'handshake',       label: 'Trusted Advisor',        text: 'You are a trusted advisor with deep experience in [domain]. You have been in this situation before — many times. You speak plainly, you do not flatter, and you give the advice you would give a close colleague.\\n\\nYour style:\\n- Lead with the hard truth if there is one\\n- Back your view with your reasoning, not just authority\\n- Acknowledge uncertainty when it exists\\n- Offer one clear recommendation, not a menu of options\\n- Ask: "What would you regret not doing?"' },
    { cat: 'personas', icon: 'brush',           label: 'Creative Director',      text: 'You are a creative director with an uncompromising aesthetic sensibility and a sharp instinct for what will land with an audience. You care deeply about craft.\\n\\nYour perspective:\\n- "Good enough" is a failure mode\\n- You push for originality over safety\\n- You ask: does this feel fresh? Does it surprise?\\n- You champion bold ideas, but you also know when something is trying too hard\\n- When you critique, you say what is not working AND you suggest what would work instead' },
    { cat: 'personas', icon: 'hub',             label: 'Systems Thinker',        text: 'You are a systems thinker. You see patterns, feedback loops, and second-order effects where others see isolated events.\\n\\nYour lens:\\n- Every outcome is the result of a system, not a single cause\\n- Ask: what reinforces this? What balances it? What delays the feedback?\\n- Map the relationships between elements before recommending a change\\n- Warn when a proposed solution shifts the problem rather than solving it\\n- Use causal diagrams and stock-and-flow thinking when useful' },
    { cat: 'personas', icon: 'favorite',        label: 'Empathetic Coach',       text: 'You are an empathetic coach who believes every person has the capacity to solve their own problems when given the right support.\\n\\nYour approach:\\n- Start by understanding before advising\\n- Reflect feelings back: "It sounds like you are feeling..."\\n- Ask permission before offering suggestions\\n- Focus on strengths and what is already working\\n- Do not rush to fix — sometimes people need to be heard before they are ready for solutions\\n- Close every session with one concrete next step the person chooses for themselves' },
    { cat: 'personas', icon: 'edit',            label: 'Hard-Nosed Editor',      text: 'You are a hard-nosed editor at a serious publication. Your job is not to be kind — it is to make the work as strong as possible.\\n\\nYour rules:\\n- Flag weak arguments, buried leads, and unsupported claims\\n- Cut anything that does not earn its place\\n- Challenge every passive construction and every vague qualifier\\n- Ask: what is the real point? Say it first.\\n- Do not rewrite — mark what is wrong and why, then let the writer fix it\\n- Praise is only given when it is genuinely earned' },
    { cat: 'personas', icon: 'rocket_launch',   label: 'Optimist Challenger',    text: 'You are an optimist challenger — you believe the upside is usually larger than people imagine, but you challenge people to actually pursue it rather than settling.\\n\\nYour stance:\\n- Default assumption: this is more achievable than it looks\\n- Challenge pessimistic framing: "Why not both? Why not 10x?"\\n- Push for the ambitious version of the plan\\n- But also: be honest about what it takes to get there\\n- Ask: what would you do if you knew you could not fail?\\n- Then: what is the smallest step that proves that direction is right?' },
    { cat: 'personas', icon: 'terminal',        label: 'Technical Lead',         text: 'You are a technical lead with strong opinions, grounded in production experience. You have built systems that failed and learned exactly why.\\n\\nYour style:\\n- Prefer simple and boring over clever and fragile\\n- Ask: what happens when this breaks at 3am?\\n- Push back on over-engineering and premature abstraction\\n- Prioritise: correctness, then simplicity, then performance\\n- When reviewing: explain the risk, not just the rule\\n- You mentor, you do not lecture — the difference is whether the other person is learning or just nodding' },
    { cat: 'personas', icon: 'support_agent',   label: 'Customer Champion',      text: 'You are a customer champion — the voice of the user inside every decision. You have talked to hundreds of customers and you know their frustrations better than they can articulate them.\\n\\nYour role:\\n- Translate business language into user experience consequences\\n- Ask: how does this decision feel from the customer side?\\n- Identify the gap between what the product team thinks the user wants and what they actually need\\n- Surface edge cases that real users will hit\\n- Your measure of success: would a real customer say "finally someone gets it"?' },
    { cat: 'personas', icon: 'corporate_fare',  label: 'Executive Briefer',      text: 'You are an executive briefer. Your job is to distill complexity into the minimum information an executive needs to make a decision.\\n\\nYour format:\\n- Situation: [one sentence on what is happening]\\n- Implication: [one sentence on why it matters]\\n- Options: [max 3, clearly labelled]\\n- Recommendation: [one clear recommendation with the key reason]\\n- Ask of the executive: [exactly what decision or action you need from them]\\n\\nNo background, no hedging, no passive voice. If they need more detail, they will ask.' },
    { cat: 'personas', icon: 'biotech',         label: 'Research Analyst',       text: 'You are a rigorous research analyst. You live by evidence and distrust conclusions that outrun their data.\\n\\nYour approach:\\n- Separate facts from interpretations — label each clearly\\n- Cite your sources (or flag when something cannot be sourced)\\n- Quantify where possible: "significant" is not a number\\n- Present the strongest counterargument before your conclusion\\n- Distinguish correlation from causation explicitly\\n- When uncertain: say how uncertain, and what information would resolve it' },
    { cat: 'personas', icon: 'route',           label: 'Product Strategist',     text: 'You are a product strategist with a rare ability to see both the user problem and the business model at the same time.\\n\\nYour lens:\\n- Start with: who has this problem so badly they are already solving it themselves?\\n- Ask: what does winning look like in 3 years, and what must be true to get there?\\n- Challenge features that do not connect to retention, growth, or monetisation\\n- Distinguish: what users say they want vs. what behaviour shows they actually value\\n- Your deliverable: a crisp point of view on what to build, and why now, and for whom' },

    // ── META (additional) ─────────────────────────────────────────────────────
    { cat: 'meta', icon: 'bug_report',          label: 'Prompt Debugger',        text: 'Debug the following prompt. Identify why it may not be producing the intended output.\\n\\nPrompt to debug:\\n[paste prompt here]\\n\\nExpected output: [what you wanted the AI to produce]\\nActual output: [what the AI actually produced]\\n\\nDiagnosis:\\n1. Ambiguity: [any unclear instructions?]\\n2. Missing context: [what did the AI not know?]\\n3. Format mismatch: [was the output format unspecified?]\\n4. Conflicting instructions: [do any parts contradict each other?]\\n5. Scope creep: [did the prompt invite too much or too little?]\\n\\nFixed prompt: [corrected version]' },
    { cat: 'meta', icon: 'speed',               label: 'Prompt Benchmarker',     text: 'Run the following prompt against 3 variations and compare results.\\n\\nBase prompt: [paste prompt here]\\n\\nVariation A — [change description]:\\n[variation]\\n\\nVariation B — [change description]:\\n[variation]\\n\\nVariation C — [change description]:\\n[variation]\\n\\nEvaluation criteria:\\n- Accuracy: does it get the right answer?\\n- Completeness: does it cover everything needed?\\n- Format: does it match the required structure?\\n- Efficiency: is it the shortest path to the goal?\\n\\nWinner: [which variation scored highest, and why]' },
    { cat: 'meta', icon: 'blur_on',             label: 'Ambiguity Detector',     text: 'Scan the following prompt for ambiguity. For every ambiguous word, phrase, or instruction, flag it and explain what different readers might interpret it to mean.\\n\\nPrompt to analyse:\\n[paste prompt here]\\n\\nAmbiguities found:\\n1. "[ambiguous phrase]" — could mean: [interpretation A] or [interpretation B]\\n2. "[ambiguous phrase]" — could mean: [interpretation A] or [interpretation B]\\n...\\n\\nHighest-risk ambiguity: [the one most likely to cause a wrong output]\\nClarified version: [prompt rewritten to remove all ambiguity]' },
    { cat: 'meta', icon: 'fork_right',          label: 'Inference Chain',        text: 'Map the reasoning chain from the input to the desired output for this prompt.\\n\\nPrompt: [paste prompt here]\\n\\nInference chain:\\nStep 1: [what the AI must first understand or establish]\\nStep 2: [what it must reason from that]\\nStep 3: [what it then needs to conclude]\\nStep 4: [how that conclusion maps to the output format]\\n\\nWeak links in the chain: [where the reasoning could break]\\nStrengthening additions: [what to add to the prompt to support each weak link]' },
    { cat: 'meta', icon: 'science',             label: 'Hypothesis Generator',   text: 'Generate [N] testable hypotheses about the following question or observation:\\n\\nQuestion/Observation: [paste here]\\n\\nFor each hypothesis:\\n- Statement: [clear, falsifiable claim]\\n- Prediction: [what would be true if this hypothesis is correct]\\n- Test: [how you would test or disprove it]\\n- Prior probability: [high / medium / low — your confidence before testing]\\n\\nRank the hypotheses from most to least likely. Lead with the one most worth testing first.' },
    { cat: 'meta', icon: 'quiz',                label: 'Probe Questions',        text: 'Generate [N] probing questions to help uncover the real problem behind the stated one.\\n\\nStated problem: [what the person said the problem is]\\n\\nProbe questions (go deeper with each one):\\n1. [surface clarification]\\n2. [challenge the framing]\\n3. [explore the root cause]\\n4. [uncover hidden assumptions]\\n5. [reveal what success would actually look like]\\n...\\n\\nMost revealing question: [the one that would most change the approach if answered]' },
    { cat: 'meta', icon: 'loop',                label: 'Self-Critique Loop',     text: 'Generate a response, critique it rigorously, then generate a final improved version.\\n\\nTask: [your task here]\\n\\nFirst attempt:\\n[generate response]\\n\\nSelf-critique:\\n- What is weakest about this response?\\n- What assumptions did I make that might be wrong?\\n- What important angle did I miss?\\n- What would a sceptical reader object to?\\n- How does this compare to the best possible response?\\n\\nFinal version (incorporating all critique):\\n[improved response]' },
    { cat: 'meta', icon: 'compress',            label: 'Prompt Minimizer',       text: 'Strip this prompt down to its essential minimum without losing capability.\\n\\nOriginal prompt:\\n[paste prompt here]\\n\\nMinimization process:\\n1. Remove all instructions the model will follow by default anyway\\n2. Remove all redundant restatements of the same rule\\n3. Compress verbose instructions into tighter phrasing\\n4. Remove examples if the task is simple enough without them\\n5. Test the minimal version to verify output quality is maintained\\n\\nMinimal version:\\n[stripped-down prompt]\\n\\nWhat was removed and why: [list with reasoning]' },
    { cat: 'meta', icon: 'search',              label: 'Assumption Finder',      text: 'Identify every assumption embedded in the following prompt or plan.\\n\\nContent to analyse:\\n[paste here]\\n\\nAssumptions found:\\n1. [assumption] — Confidence: [high/med/low] — Risk if wrong: [high/med/low]\\n2. [assumption] — Confidence: [high/med/low] — Risk if wrong: [high/med/low]\\n3. [assumption] — Confidence: [high/med/low] — Risk if wrong: [high/med/low]\\n...\\n\\nMost dangerous assumption: [the one that, if wrong, breaks the whole approach]\\nHow to validate it: [fastest way to test this assumption]' },
    { cat: 'meta', icon: 'preview',             label: 'Output Predictor',       text: 'Predict what output this prompt will produce before running it.\\n\\nPrompt to analyse:\\n[paste prompt here]\\n\\nPredicted output characteristics:\\n- Format: [what structure the output will have]\\n- Length: [estimated length]\\n- Tone: [predicted tone and register]\\n- Content: [main points it will likely cover]\\n- What it will miss: [gaps or blind spots]\\n- Risk of hallucination: [high / medium / low — and why]\\n\\nSurprise prediction: [the most unexpected thing this prompt might produce]' },
    { cat: 'meta', icon: 'tune',                label: 'Tone Calibrator',        text: 'Rewrite the following prompt to produce output with a specific tone.\\n\\nOriginal prompt:\\n[paste prompt here]\\n\\nTarget tone: [e.g. executive-formal / conversational-warm / technical-precise / persuasive-energetic]\\n\\nTone dimensions to adjust:\\n- Formality: [1=casual, 5=formal] Target: [N]\\n- Directness: [1=diplomatic, 5=blunt] Target: [N]\\n- Detail level: [1=summary, 5=exhaustive] Target: [N]\\n- Emotional warmth: [1=cold, 5=warm] Target: [N]\\n\\nCalibrated prompt:\\n[rewritten to produce target tone]' },
    { cat: 'meta', icon: 'groups',              label: 'Audience Adapter',       text: 'Rewrite this prompt to produce output appropriate for a different audience.\\n\\nOriginal prompt:\\n[paste prompt here]\\n\\nTarget audience: [describe them — role, expertise level, what they care about, what they already know]\\n\\nAdaptations to make:\\n1. Vocabulary: [technical → plain / plain → technical / specialist jargon → general]\\n2. Examples: [use examples relevant to their world]\\n3. Format: [what format this audience prefers — bullets / prose / tables]\\n4. Depth: [how much background do they need?]\\n5. CTA: [what should they do with this information?]\\n\\nAdapted prompt:\\n[rewritten version]' },
    { cat: 'meta', icon: 'filter_none',         label: 'Context Stripper',       text: 'Identify and remove all context from this prompt that the AI does not actually need to complete the task.\\n\\nOriginal prompt:\\n[paste prompt here]\\n\\nContext audit:\\n- Essential context (keep): [list]\\n- Helpful but optional (mark as optional): [list]\\n- Irrelevant / adds noise (remove): [list]\\n- Context that might bias the output (flag): [list]\\n\\nCleaned prompt (minimum necessary context only):\\n[stripped version]\\n\\nNote: Always test stripped prompts to confirm quality is maintained.' },
    { cat: 'meta', icon: 'category',            label: 'Task Classifier',        text: 'Classify the following task to determine the optimal prompting strategy.\\n\\nTask description:\\n[paste here]\\n\\nClassification:\\n- Task type: [generation / classification / extraction / transformation / reasoning / dialogue]\\n- Complexity: [simple / multi-step / requires planning]\\n- Output type: [text / list / table / JSON / code / decision]\\n- Domain knowledge required: [general / specialist — specify domain]\\n- Ambiguity level: [low / medium / high]\\n\\nRecommended prompt pattern: [which prompting technique fits best and why]\\nKey risks to address in the prompt: [what could go wrong]' },
    { cat: 'meta', icon: 'insights',            label: 'Prompt ROI Analyser',    text: 'Evaluate the effort-to-value ratio of this prompt. Is it worth the complexity?\\n\\nPrompt to evaluate:\\n[paste prompt here]\\n\\nComplexity cost:\\n- Word count: [N words]\\n- Token estimate: [~N tokens]\\n- Instructions to follow: [count]\\n- Edge cases handled: [count]\\n\\nValue delivered:\\n- Core task: [the actual thing you need it to do]\\n- Extra constraints add: [what value do they add?]\\n- Simplification opportunity: [what could be removed with minimal quality loss?]\\n\\nVerdict: [over-engineered / right-sized / under-specified] — [one sentence why]' },

    // ── PROMPT ENGINEERING (new category) ────────────────────────────────────
    { cat: 'prompteng', icon: 'looks_one',      label: 'Zero-Shot Instruction',  text: 'Write a zero-shot prompt for the following task. No examples — the instruction must be precise enough to work on its own.\\n\\nTask: [[task]]\\nOutput format: [[format]]\\nConstraints: [[constraints]]\\n\\nZero-shot prompt:\\n[clear instruction that specifies role, task, format, and constraints — all without examples]' },
    { cat: 'prompteng', icon: 'looks_two',      label: 'One-Shot Template',      text: 'Task: [describe the task]\\n\\nHere is one example to show the pattern:\\n\\nInput: [example input]\\nOutput: [ideal output that demonstrates the pattern perfectly]\\n\\nNow apply this to the actual input:\\nInput: [[input]]\\nOutput:' },
    { cat: 'prompteng', icon: 'format_list_numbered', label: 'Few-Shot Pattern', text: 'Task: [describe the task]\\n\\nExamples:\\n\\nInput: [example 1 — standard case]\\nOutput: [ideal output 1]\\n\\nInput: [example 2 — edge case]\\nOutput: [ideal output 2]\\n\\nInput: [example 3 — tricky case]\\nOutput: [ideal output 3]\\n\\nNow complete:\\nInput: [[input]]\\nOutput:' },
    { cat: 'prompteng', icon: 'account_tree',   label: 'Tree of Thoughts',       text: "Solve the following problem by exploring multiple reasoning paths before committing to a solution.\\n\\nProblem: [[problem]]\\n\\nThought tree:\\n\\nBranch A — [approach 1]:\\n  Step A1: [reasoning]\\n  Step A2: [reasoning]\\n  Conclusion A: [where this leads]\\n  Viability: [strong/weak — why]\\n\\nBranch B — [approach 2]:\\n  Step B1: [reasoning]\\n  Step B2: [reasoning]\\n  Conclusion B: [where this leads]\\n  Viability: [strong/weak — why]\\n\\nBest path: [chosen branch + key reason]\\nFinal answer: [conclusion from best path]" },
    { cat: 'prompteng', icon: 'all_inclusive',  label: 'Self-Consistency',       text: 'Solve the following problem independently 3 times using different reasoning paths. Then identify the answer that appears most consistently.\\n\\nProblem: [[problem]]\\n\\nAttempt 1 (direct approach):\\n[reasoning + answer]\\n\\nAttempt 2 (alternative approach):\\n[reasoning + answer]\\n\\nAttempt 3 (contrarian approach):\\n[reasoning + answer]\\n\\nConsistency check: [which answer appeared most often?]\\nFinal answer: [most consistent result, or note if all differ and why]' },
    { cat: 'prompteng', icon: 'steps',          label: 'Step-Back Prompting',    text: 'Before answering the specific question, first answer the broader principle behind it.\\n\\nSpecific question: [[specific_question]]\\n\\nStep back — the broader principle:\\n[What general principle, rule, or framework is relevant here?]\\n\\nApply the principle to the specific case:\\n[Now answer the original question using the principle as your foundation]' },
    { cat: 'prompteng', icon: 'auto_awesome',   label: 'Generated Knowledge',    text: 'Before answering the question below, first generate the key facts and knowledge you would need to answer it well. Then use that knowledge to form your answer.\\n\\nQuestion: [[question]]\\n\\nRelevant knowledge to generate first:\\n1. [key fact or concept]\\n2. [key fact or concept]\\n3. [key fact or concept]\\n4. [key fact or concept]\\n\\nNow use this knowledge to answer:\\n[answer grounded in the generated knowledge]' },
    { cat: 'prompteng', icon: 'link',           label: 'Prompt Chaining',        text: 'This is step [[step_number]] of [[total_steps]] in a prompt chain.\\n\\nOutput from previous step:\\n[[previous_output]]\\n\\nYour task for this step:\\n[[current_task]]\\n\\nInput you are working with:\\n[[current_input]]\\n\\nOutput format for this step:\\n[[output_format]]\\n\\nNote: Your output from this step will be passed directly as input to the next step. Do not include explanation or commentary — just the output.' },
    { cat: 'prompteng', icon: 'view_comfy',     label: 'Role+Task+Format',       text: 'ROLE: You are a [[role]] with expertise in [[domain]]\\n\\nTASK: [[clear_task_instruction]]\\n\\nCONTEXT: [[relevant_background]]\\n\\nCONSTRAINTS:\\n- [[constraint_1]]\\n- [[constraint_2]]\\n- [[constraint_3]]\\n\\nFORMAT: Return your response as:\\n[[format_specification]]\\n\\nEXAMPLE: [[optional_example]]' },
    { cat: 'prompteng', icon: 'settings',       label: 'System Prompt Frame',    text: 'You are [[name]], an AI assistant specialised in [[domain]].\\n\\nYour primary purpose: [[main_purpose]]\\n\\nYou ALWAYS:\\n- [[always_rule_1]]\\n- [[always_rule_2]]\\n- [[always_rule_3]]\\n\\nYou NEVER:\\n- [[never_rule_1]]\\n- [[never_rule_2]]\\n\\nYour tone: [[tone_description]]\\nYour output format: [[format_description]]\\n\\nWhen you are uncertain: [[uncertainty_handling]]\\nWhen asked to go outside your scope: [[scope_handling]]' },
    { cat: 'prompteng', icon: 'data_object',    label: 'Output Spec Block',      text: 'Return your response in the following format ONLY. No additional text, explanation, or commentary outside this structure.\\n\\nFORMAT SPECIFICATION:\\n{\\n  "field_1": "[description of what goes here — type: string]",\\n  "field_2": "[description — type: number]",\\n  "field_3": "[description — type: array of strings]",\\n  "field_4": {\\n    "nested_field": "[description — type: string]"\\n  }\\n}\\n\\nConstraints:\\n- field_1 must be [[constraint]]\\n- field_3 must contain exactly [[N]] items\\n- If a field value is unknown, use null' },
    { cat: 'prompteng', icon: 'token',          label: 'Token Budget',           text: 'Complete the following task within a strict token budget.\\n\\nTask: [[task]]\\nToken budget: approximately [[N]] tokens\\n\\nPrioritisation rules (in order):\\n1. Cover: [[most_important_element]] — never cut this\\n2. Include if space: [[second_priority]]\\n3. Include if space: [[third_priority]]\\n4. Omit if budget is tight: [[lowest_priority]]\\n\\nIf you must choose between completeness and staying within budget, prefer completeness for items 1-2 and sacrifice items 3-4.' },
    { cat: 'prompteng', icon: 'contrast',       label: 'Contrastive Examples',   text: 'Use contrasting examples to demonstrate the difference between correct and incorrect output.\\n\\nTask: [[task]]\\n\\nBad example (what NOT to produce):\\nInput: [example]\\nWrong output: [bad output]\\nWhy it is wrong: [explanation]\\n\\nGood example (what TO produce):\\nInput: [example]\\nCorrect output: [good output]\\nWhy it is right: [explanation]\\n\\nNow complete:\\nInput: [[input]]\\nCorrect output:' },
    { cat: 'prompteng', icon: 'anchor',         label: 'Prompt Anchoring',       text: 'ANCHOR STATEMENT — read this before processing the request:\\n\\n[State the most important constraint, value, or perspective that must frame all responses]\\n\\nThis anchor overrides any conflicting instruction in the conversation. Every response you give must be consistent with this anchor.\\n\\nAnchor: [[anchor_statement]]\\n\\nTo verify you have understood: briefly restate the anchor in your own words before proceeding.' },
    { cat: 'prompteng', icon: 'analytics',      label: 'Retrieval Augmentation', text: 'Use the following retrieved context to answer the question. Do not use knowledge outside of what is provided.\\n\\nRetrieved context (relevance score: [[score]]):\\n---\\n[[retrieved_content]]\\n---\\n\\nQuestion: [[question]]\\n\\nAnswer (based only on the retrieved context above):\\n[your answer]\\n\\nConfidence: [[high/medium/low]] — [brief reason]\\nGaps: [what the retrieved context did not cover that would have helped]' },
    { cat: 'prompteng', icon: 'difference',     label: 'A/B Prompt Variant',     text: 'This is variant [[A or B]] of an A/B test.\\n\\nHypothesis being tested: [[what_you_are_testing — e.g. "does adding a role improve specificity?"]]\\n\\nVariant A — Control:\\n[[control_prompt]]\\n\\nVariant B — Treatment:\\n[[treatment_prompt]]\\n\\nEvaluation criteria (score each 1-5):\\n- Accuracy\\n- Completeness\\n- Format adherence\\n- Tone match\\n\\nWinner: [A or B] — [one sentence on why, citing the evaluation scores]' },
    { cat: 'prompteng', icon: 'stars',          label: 'Calibration Block',      text: 'Before answering, calibrate your response to the following parameters:\\n\\nExpertise of the reader: [[beginner / intermediate / expert]]\\nPurpose of the output: [[inform / persuade / instruct / entertain]]\\nTime budget of the reader: [[30 seconds / 2 minutes / deep read]]\\nAction required after reading: [[decide / act / share / store]]\\n\\nCalibration decisions you should make based on the above:\\n- Vocabulary level: [your choice]\\n- Depth: [your choice]\\n- Format: [your choice]\\n- Length: [your choice]' },
    { cat: 'prompteng', icon: 'manage_history', label: 'Prompt Versioning',      text: '--- PROMPT v[[version_number]] ---\\nLast updated: [[date]]\\nChange from previous: [[what_changed_and_why]]\\n\\n[PROMPT CONTENT]\\n[[your_prompt_here]]\\n\\n[END PROMPT]\\n\\nKnown limitations of this version:\\n- [[limitation_1]]\\n- [[limitation_2]]\\n\\nNext planned improvement:\\n[[what_to_try_in_the_next_version]]' },

    // ── USE CASE LIBRARY (new category) ──────────────────────────────────────
    { cat: 'usecases', icon: 'article',         label: 'Blog Post Brief',        text: 'Create a blog post on the following topic.\\n\\nTopic: [[topic]]\\nAudience: [[audience]]\\nGoal: [[goal — e.g. educate / inspire / drive sign-ups]]\\nWord count: [[word_count]]\\nTone: [[tone]]\\nSEO target keyword: [[keyword]]\\n\\nStructure: hook → problem → insight → practical steps → conclusion + CTA\\n\\nDo not write the post yet — produce the full outline first. Confirm the outline before writing.' },
    { cat: 'usecases', icon: 'share',           label: 'Social Media Suite',     text: 'Write a social media content suite for: [[topic]]\\n\\nBrand voice: [[brand_voice]]\\nCampaign goal: [[goal]]\\n\\nDeliver:\\n1. Twitter/X thread (7 tweets, hook + 5 insights + CTA)\\n2. LinkedIn post (250-350 words, insight-led)\\n3. Instagram caption (visual-first, 3 emojis max, hashtags at end)\\n4. Facebook post (conversational, 150 words)\\n5. Short-form video script (60 seconds, spoken word)\\n\\nAll posts should feel native to their platform.' },
    { cat: 'usecases', icon: 'mail',            label: 'Email Campaign',         text: 'Write a 3-email campaign for [[goal — e.g. product launch / re-engagement / onboarding]].\\n\\nProduct/Service: [[product]]\\nAudience: [[audience]]\\nCampaign timeline: [[timeline]]\\n\\nEmail 1 — [Day 0]: [subject line] + [body outline]\\nEmail 2 — [Day 3]: [subject line] + [body outline]\\nEmail 3 — [Day 7]: [subject line] + [body outline]\\n\\nEach email: subject line, preview text, body (max 200 words), one CTA.' },
    { cat: 'usecases', icon: 'web',             label: 'Landing Page Copy',      text: 'Write landing page copy for [[product_or_service]].\\n\\nTarget visitor: [[visitor_type]]\\nMain pain point: [[pain_point]]\\nCore benefit: [[benefit]]\\nSocial proof available: [[proof — testimonials, stats, logos]]\\nCTA action: [[cta]]\\n\\nSections to write:\\n- Hero (headline + subheading + CTA button)\\n- Problem statement (2-3 sentences)\\n- Solution (3 benefit bullets with icons)\\n- Social proof block\\n- Feature breakdown (3 features, benefit-first)\\n- Final CTA section' },
    { cat: 'usecases', icon: 'campaign',        label: 'Ad Campaign Brief',      text: 'Create an ad campaign brief for [[campaign_name]].\\n\\nProduct: [[product]]\\nAudience: [[audience]]\\nBudget: [[budget]]\\nDuration: [[duration]]\\nGoal: [[goal — awareness / conversions / retention]]\\n\\nCampaign brief:\\n- Campaign concept (2 sentences)\\n- Core message\\n- Channels (ranked by priority)\\n- Creative direction\\n- Key metrics (what we will measure)\\n- What success looks like\\n- Constraints (what we must not do)' },
    { cat: 'usecases', icon: 'calendar_month',  label: 'Content Calendar',       text: 'Plan a [[duration]]-week content calendar for [[brand_or_project]].\\n\\nChannels: [[channels]]\\nContent themes: [[themes]]\\nPosting frequency: [[frequency]]\\n\\nCalendar format:\\nWeek 1:\\n  Mon: [content type] — [topic] — [channel]\\n  Wed: [content type] — [topic] — [channel]\\n  Fri: [content type] — [topic] — [channel]\\n\\n[Repeat for each week]\\n\\nContent mix target: [[N]]% educational, [[N]]% promotional, [[N]]% engagement' },
    { cat: 'usecases', icon: 'video_library',   label: 'YouTube Script',         text: 'Write a YouTube script for a [[length]]-minute video on: [[topic]]\\n\\nChannel audience: [[audience]]\\nVideo goal: [[goal]]\\nCall to action: [[cta]]\\n\\nScript structure:\\n[HOOK 0:00-0:30] — Pattern interrupt + promise\\n[INTRO 0:30-1:00] — What you will cover, why it matters\\n[MAIN CONTENT 1:00-[[length minus 1]]min] — [3-5 sections with timestamps]\\n[CTA [[final minute]]] — Subscribe / like / comment prompt + next video tease\\n\\nInclude: B-roll suggestions in [brackets]' },
    { cat: 'usecases', icon: 'mic',             label: 'Podcast Episode Plan',   text: 'Plan a podcast episode on: [[topic]]\\n\\nShow format: [[format — interview / solo / roundtable]]\\nEpisode length: [[length]] minutes\\nGuest (if any): [[guest_name]], [[guest_credentials]]\\n\\nEpisode structure:\\n- Hook (first 60 seconds)\\n- Guest intro / context\\n- Interview arc (5-7 questions with follow-up notes)\\n- Key insights to hit\\n- Sponsor segment placement\\n- Outro + CTA\\n\\nShow notes (50 words):\\nTime-stamped chapters:\\nSocial clip opportunities (3):' },
    { cat: 'usecases', icon: 'description',     label: 'Product Description',    text: 'Write a product description for [[product_name]].\\n\\nBuyer persona: [[persona]]\\nKey features: [[features]]\\nPrimary benefit: [[benefit]]\\nTone: [[tone]]\\nChannel: [[where this will appear — website / Amazon / catalogue]]\\n\\nWrite:\\n1. Short version (25 words max — for cards / listings)\\n2. Medium version (75 words — for product page above the fold)\\n3. Long version (200 words — full page description with features table)' },
    { cat: 'usecases', icon: 'person_search',   label: 'User Story Set',         text: 'Write a set of user stories for [[feature_or_product]].\\n\\nPersonas to cover: [[personas]]\\nCore functionality: [[functionality]]\\n\\nFormat for each story:\\n- As a [persona], I want to [action] so that [outcome]\\n- Acceptance criteria: [3-5 testable conditions]\\n- Priority: [Must Have / Should Have / Could Have / Will Not Have]\\n- Notes: [edge cases or assumptions]\\n\\nWrite [[N]] stories covering the full feature scope.' },
    { cat: 'usecases', icon: 'assignment',      label: 'Product Requirements',   text: 'Write a product requirements document (PRD) for: [[feature_name]]\\n\\nProduct: [[product]]\\nOwner: [[owner]]\\nTarget launch: [[launch_date]]\\n\\nSections:\\n1. Problem statement\\n2. Goals and success metrics\\n3. User stories (minimum 5)\\n4. Functional requirements\\n5. Non-functional requirements\\n6. Out of scope\\n7. Dependencies\\n8. Open questions\\n9. Timeline' },
    { cat: 'usecases', icon: 'code',            label: 'Technical Spec',         text: 'Write a technical specification for: [[feature_name]]\\n\\nSystem: [[system]]\\nTech stack: [[stack]]\\nEngineer audience: [[level]]\\n\\nSections:\\n1. Overview (what and why)\\n2. Architecture diagram (describe in words)\\n3. API design (endpoints, request/response)\\n4. Data model (schema changes)\\n5. Edge cases and error handling\\n6. Security considerations\\n7. Performance requirements\\n8. Testing plan\\n9. Rollout plan' },
    { cat: 'usecases', icon: 'bug_report',      label: 'Bug Report Template',    text: 'File a complete bug report for the following issue:\\n\\nTitle: [[short_description]]\\n\\nEnvironment:\\n- OS: [[os]]\\n- Browser/App version: [[version]]\\n- User account type: [[account_type]]\\n\\nSteps to reproduce:\\n1. [step]\\n2. [step]\\n3. [step]\\n\\nExpected behaviour: [[expected]]\\nActual behaviour: [[actual]]\\nFrequency: [[always / sometimes / once]]\\nSeverity: [[critical / high / medium / low]]\\nScreenshots/logs: [[attached / not available]]' },
    { cat: 'usecases', icon: 'query_stats',     label: 'Data Analysis Request',  text: 'Analyse the following data and answer the question.\\n\\nData (paste below):\\n[[data]]\\n\\nQuestion to answer: [[question]]\\n\\nAnalysis requirements:\\n- Identify the key trend or pattern\\n- Flag any anomalies or outliers\\n- Provide the top 3 insights\\n- Recommend one action based on the data\\n\\nOutput format: [[table / bullet points / paragraph / chart spec]]' },
    { cat: 'usecases', icon: 'summarize',       label: 'Report Builder',         text: 'Build a report on the following topic.\\n\\nTopic: [[topic]]\\nAudience: [[audience]]\\nData/sources available: [[sources]]\\n\\nReport structure:\\n1. Executive summary (5 bullets)\\n2. Key findings (ranked by impact)\\n3. Analysis (what the data means)\\n4. Recommendations (actionable, numbered)\\n5. Appendix (methodology, data sources)\\n\\nLength: [[length]]\\nTone: [[tone — formal / analytical / accessible]]' },
    { cat: 'usecases', icon: 'trending_up',     label: 'Market Research Brief',  text: 'Produce a market research brief for [[market_or_product]].\\n\\nBusiness question: [[question]]\\nTimeframe: [[timeframe]]\\nBudget: [[budget]]\\n\\nResearch plan:\\n1. Research objectives (3-5 specific questions to answer)\\n2. Methodology (primary vs secondary research)\\n3. Target respondents (who to survey/interview)\\n4. Data sources to use\\n5. Deliverables\\n6. Timeline\\n7. Success criteria' },
    { cat: 'usecases', icon: 'compare',         label: 'Competitive Analysis',   text: 'Run a competitive analysis for [[product]] against [[competitors]].\\n\\nAnalysis dimensions:\\n1. Product features (comparison table)\\n2. Pricing model\\n3. Target customer\\n4. Go-to-market approach\\n5. Strengths (what each competitor does best)\\n6. Weaknesses (where they fall short)\\n7. Our differentiation opportunity\\n\\nOutput: full comparison table + one-paragraph positioning recommendation' },
    { cat: 'usecases', icon: 'record_voice_over', label: 'Customer Interview',   text: 'Prepare and run a customer interview for [[research_goal]].\\n\\nCustomer profile: [[profile]]\\nKey questions to answer: [[questions]]\\n\\nInterview guide:\\n- Warm-up (5 min): [questions to build rapport]\\n- Core exploration (20 min): [5-7 deep questions]\\n- Problem deep-dive (10 min): [follow-up probes]\\n- Wrap-up (5 min): [synthesis + permission to follow up]\\n\\nNote-taking template:\\nKey quotes:\\nSurprises:\\nPatterns to explore:' },
    { cat: 'usecases', icon: 'checklist',       label: 'Survey Designer',        text: 'Design a survey for [[survey_goal]].\\n\\nTarget respondents: [[respondents]]\\nExpected completion time: [[time]] minutes\\nDelivery method: [[email / in-app / phone]]\\n\\nSurvey sections:\\n1. Screener (2 questions)\\n2. Background (2-3 questions)\\n3. Core topic (5-7 questions)\\n4. Rating scales (NPS / CSAT / custom)\\n5. Open-ended qualitative (1-2 questions)\\n\\nFor each question: text + format + why it is included' },
    { cat: 'usecases', icon: 'workspace_premium', label: 'Case Study Builder',   text: 'Write a case study for the following success story.\\n\\nCustomer: [[customer]]\\nIndustry: [[industry]]\\nChallenge: [[challenge]]\\nSolution: [[solution_provided]]\\nResult: [[measurable_result]]\\nTimeline: [[timeframe]]\\nQuote approved: [[quote]]\\n\\nStructure: headline → challenge section → solution section → results section → customer quote → about section\\nLength: [[length]] words\\nUse: [[website / sales deck / press]]' },
    { cat: 'usecases', icon: 'local_library',   label: 'White Paper',            text: 'Outline a white paper on: [[topic]]\\n\\nTarget reader: [[reader_title]] at [[company_type]]\\nCore argument: [[argument]]\\nData available: [[data]]\\n\\nWhite paper structure:\\n1. Executive summary\\n2. Industry context and problem\\n3. Why existing solutions fall short\\n4. Our perspective / framework\\n5. Evidence and case examples\\n6. Recommendations\\n7. Conclusion\\n\\nTone: authoritative, evidence-based\\nLength: [[N]] pages\\nCall to action: [[cta]]' },
    { cat: 'usecases', icon: 'handshake',       label: 'Partnership Proposal',   text: 'Write a partnership proposal from [[our_company]] to [[partner_company]].\\n\\nPartnership type: [[type — co-marketing / integration / referral / JV]]\\nMutual benefit: [[what both parties gain]]\\nAsk: [[what we want from them]]\\nOffer: [[what we bring to the table]]\\n\\nStructure:\\n1. Why this partnership makes sense (strategic fit)\\n2. What we propose (specific terms)\\n3. What we each bring\\n4. Success metrics\\n5. Proposed next steps\\n\\nTone: direct, collegial, mutually focused' },
    { cat: 'usecases', icon: 'meeting_room',    label: 'Meeting Agenda',         text: 'Create a meeting agenda for: [[meeting_title]]\\n\\nDate/time: [[datetime]]\\nAttendees: [[attendees]]\\nMeeting goal: [[goal]]\\nDuration: [[duration]] minutes\\n\\nAgenda:\\n[Time] Welcome + objective (5 min)\\n[Time] [[agenda_item_1]] — Owner: [[owner]] (N min)\\n[Time] [[agenda_item_2]] — Owner: [[owner]] (N min)\\n[Time] [[agenda_item_3]] — Owner: [[owner]] (N min)\\n[Time] Decisions needed (10 min)\\n[Time] Next steps + owners (5 min)\\n\\nPre-read materials: [[prereads]]' },
    { cat: 'usecases', icon: 'work',            label: 'Job Description',        text: 'Write a job description for: [[job_title]]\\n\\nTeam: [[team]]\\nLevel: [[level]]\\nLocation: [[location_or_remote]]\\nSalary range: [[range]]\\n\\nSections:\\n- About the role (3 sentences)\\n- What you will do (5-7 responsibility bullets)\\n- What we are looking for\\n  Must have: [[must_haves]]\\n  Nice to have: [[nice_to_haves]]\\n- What we offer (benefits + culture)\\n- About us (2 sentences)\\n\\nTone: [[company_tone]] — no jargon, inclusive language' },
    { cat: 'usecases', icon: 'rate_review',     label: 'Performance Review',     text: 'Write a performance review for [[employee_name]] for [[period]].\\n\\nRole: [[role]]\\nKey objectives for the period: [[objectives]]\\nAchievements: [[achievements]]\\nAreas for growth: [[areas_to_develop]]\\nRating: [[rating]]\\n\\nSections:\\n1. Overall summary (3 sentences)\\n2. Achievements (specific examples with impact)\\n3. Areas for development (constructive, specific, forward-looking)\\n4. Goals for next period (3-5 SMART goals)\\n5. Rating with justification' },
    { cat: 'usecases', icon: 'how_to_reg',      label: 'Onboarding Checklist',   text: 'Create a [[duration]]-day onboarding plan for a new [[role_title]] joining [[team]].\\n\\nStart date: [[start_date]]\\nManager: [[manager]]\\nKey systems to access: [[systems]]\\n\\nDay 1: [orientation tasks]\\nWeek 1: [foundational tasks — setup, meet team, learn the product]\\nWeek 2: [ramp-up tasks — first contributions]\\nWeek 3-4: [independence tasks — first solo deliverables]\\n\\nCheckpoints: Day 7 / Day 30 / Day 90 — what should they know/be able to do at each?' },
    { cat: 'usecases', icon: 'auto_stories',    label: 'Course Outline',         text: 'Design a course outline for: [[course_title]]\\n\\nLearner: [[audience]]\\nDuration: [[duration]]\\nDelivery: [[format — video / workshop / self-paced]]\\nOutcome: By the end, learners will be able to [[outcome]]\\n\\nCourse structure:\\nModule 1: [[title]] — [[what they will learn]]\\nModule 2: [[title]] — [[what they will learn]]\\nModule 3: [[title]] — [[what they will learn]]\\nModule 4: [[title]] — [[what they will learn]]\\n\\nFor each module: key concepts, exercises, and assessment' },
    { cat: 'usecases', icon: 'help_center',     label: 'FAQ Builder',            text: 'Generate a FAQ section for [[product_or_topic]].\\n\\nTarget reader: [[reader]]\\nCommon confusion points: [[confusions]]\\nTone: [[tone — friendly / formal / technical]]\\n\\nGenerate [[N]] FAQ pairs. For each:\\nQ: [the question — phrased exactly as a user would ask it]\\nA: [direct answer in 2-4 sentences — lead with the answer, then the explanation]\\n\\nOrder: most frequently asked first. Flag which 3 questions are highest priority.' },"""

# ── 3. Build new frameworks string ────────────────────────────────────────

NEW_FRAMEWORKS = """
    { badge: 'PAS',     name: 'Problem, Agitate, Solution',          desc: 'Copywriting persuasion arc',
      text: 'Problem: [describe the pain point clearly and specifically]\\n\\nAgitate: [amplify the pain — what happens if it goes unsolved? Make the cost real]\\n\\nSolution: [present your offer as the relief — specific, credible, direct]' },
    { badge: 'BAB',     name: 'Before, After, Bridge',               desc: 'Transformation storytelling frame',
      text: 'Before: [paint the picture of their current state — the frustration, the limitation, the cost]\\n\\nAfter: [paint the picture of the ideal future state — specific and vivid]\\n\\nBridge: [how you get them from Before to After — your product, method, or solution]' },
    { badge: 'SCQA',    name: 'Situation, Complication, Question, Answer', desc: 'McKinsey narrative structure',
      text: 'Situation: [what is true right now — the stable starting context]\\n\\nComplication: [what has changed or what tension has emerged — why action is needed]\\n\\nQuestion: [the question the audience is now asking — implicit or explicit]\\n\\nAnswer: [your response, recommendation, or solution to the question]' },
    { badge: 'FOREST',  name: 'Focus, Objective, Requirements, Examples, Style, Tone', desc: 'Complete prompt specification',
      text: 'Focus: [the specific topic or domain — what this is about]\\nObjective: [what the output needs to achieve]\\nRequirements: [specific must-haves in the output]\\nExamples: [1-2 examples of ideal output or reference material]\\nStyle: [structural or formatting preferences]\\nTone: [voice, register, and personality]' },
    { badge: 'RIPER',   name: 'Role, Instruction, Parameters, Examples, Response', desc: 'Prompt architecture framework',
      text: 'Role: [who the AI is — title, expertise, perspective]\\nInstruction: [the exact task — what to do]\\nParameters: [constraints, limits, and rules — what is in and out of scope]\\nExamples: [input-output demonstrations if needed]\\nResponse format: [structure, length, and format of the desired output]' },
    { badge: '5 Whys',  name: 'Five Whys Root Cause Analysis',        desc: 'Drill to the root cause of any problem',
      text: 'Problem statement: [what went wrong — specific, observable]\\n\\nWhy 1: [why did this happen?] → Because: [answer]\\nWhy 2: [why did that happen?] → Because: [answer]\\nWhy 3: [why did that happen?] → Because: [answer]\\nWhy 4: [why did that happen?] → Because: [answer]\\nWhy 5: [why did that happen?] → Because: [ROOT CAUSE]\\n\\nRoot cause: [the underlying systemic issue]\\nFix: [what to address at the root level]' },
    { badge: 'PDCA',    name: 'Plan, Do, Check, Act',                 desc: 'Continuous improvement cycle',
      text: 'Plan: [what are you trying to improve? What is the hypothesis? What is the experiment?]\\n\\nDo: [how will you implement the plan? Who does what? Timeline?]\\n\\nCheck: [how will you measure success? What data will you collect? What does good look like?]\\n\\nAct: [if it worked: how do you standardise it? If it did not: what do you change for the next cycle?]' },
    { badge: 'GROW',    name: 'Goal, Reality, Options, Will',         desc: 'Coaching conversation framework',
      text: 'Goal: [what do you want to achieve? By when? How will you know you have got there?]\\n\\nReality: [what is the current situation? What have you tried? What is working and what is not?]\\n\\nOptions: [what could you do? Generate at least 5 options without judging them yet]\\n\\nWill: [which option will you commit to? What is the first step? When will you take it?]' },
    { badge: 'Eisenhower', name: 'Urgent vs Important Matrix',        desc: 'Prioritise by urgency and importance',
      text: 'Quadrant 1 — DO NOW (urgent + important):\\n[tasks that are both urgent and critical — do these first]\\n\\nQuadrant 2 — SCHEDULE (important + not urgent):\\n[strategic work — block time for these or they never happen]\\n\\nQuadrant 3 — DELEGATE (urgent + not important):\\n[someone else can handle these — assign with clear brief]\\n\\nQuadrant 4 — ELIMINATE (not urgent + not important):\\n[cut these — they are consuming time without creating value]' },
    { badge: 'RICE',    name: 'Reach, Impact, Confidence, Effort',    desc: 'Prioritise features and initiatives',
      text: 'For each initiative, score the following:\\n\\nReach: [how many users/customers does this affect per time period? Number]\\nImpact: [how much does it move the key metric? 0.25=minimal / 0.5=low / 1=medium / 2=high / 3=massive]\\nConfidence: [how confident are you in the estimates? %]\\nEffort: [person-months to build and ship]\\n\\nRICE score = (Reach × Impact × Confidence) / Effort\\n\\nRank all initiatives by RICE score. The highest score is the highest priority.' },
    { badge: 'ICE',     name: 'Impact, Confidence, Ease',             desc: 'Fast initiative scoring',
      text: 'Score each idea 1-10 on the following dimensions:\\n\\nImpact: [how much will this move the metric that matters? 1=minimal, 10=transformative]\\nConfidence: [how confident are you it will work? 1=very uncertain, 10=almost certain]\\nEase: [how easy is it to implement? 1=very difficult, 10=trivial]\\n\\nICE score = (Impact + Confidence + Ease) / 3\\n\\nRank all ideas by ICE score. Start with the highest. Revisit lowest-ease high-impact items for future sprints.' },
    { badge: 'MoSCoW',  name: 'Must Have, Should Have, Could Have, Will Not', desc: 'Scope and requirements prioritisation',
      text: 'Must Have (non-negotiable — the product fails without these):\\n- [requirement]\\n\\nShould Have (important but not critical for launch):\\n- [requirement]\\n\\nCould Have (nice to have if time/budget allows):\\n- [requirement]\\n\\nWill Not Have (explicitly out of scope for this version):\\n- [requirement]\\n\\nNote: "Must Have" should be ≤50% of total scope. If everything is "Must Have", re-prioritise.' },
    { badge: 'RACI',    name: 'Responsible, Accountable, Consulted, Informed', desc: 'Clarify who does what on a project',
      text: 'Activity / Decision: [name the task or decision]\\n\\nResponsible (R): [who does the work — can be multiple people]\\nAccountable (A): [who owns the outcome — must be exactly ONE person]\\nConsulted (C): [who must be asked for input before the decision/action]\\nInformed (I): [who needs to be told after the decision/action]\\n\\nRule: Every activity needs exactly one A. Multiple R is OK. No A = no owner = no accountability.' },
    { badge: 'ADKAR',   name: 'Awareness, Desire, Knowledge, Ability, Reinforcement', desc: 'Change management model',
      text: 'Awareness: [do people know WHY the change is needed? How will you create awareness?]\\n\\nDesire: [do people WANT to change? What is in it for them? What resistance exists?]\\n\\nKnowledge: [do people know HOW to change? What training or information do they need?]\\n\\nAbility: [can people actually change? What support, tools, or practice do they need?]\\n\\nReinforcement: [what will keep the change in place? Recognition, metrics, feedback loops?]' },
    { badge: "Hero's Journey", name: "Hero's Journey Narrative Arc", desc: 'Classic storytelling structure',
      text: "Ordinary World: [the hero's normal life before the adventure]\\nCall to Adventure: [the problem or opportunity that disrupts it]\\nRefusal of the Call: [initial resistance or hesitation]\\nMeeting the Mentor: [the guide who gives advice, tools, or courage]\\nCrossing the Threshold: [committing to the journey]\\nTests, Allies, Enemies: [the challenges faced along the way]\\nThe Ordeal: [the darkest moment — the biggest test]\\nThe Reward: [what is gained from surviving the ordeal]\\nThe Road Back: [the return, with a new challenge]\\nResurrection: [the final test — proving the transformation]\\nReturn with the Elixir: [bringing the gift back to the ordinary world]" },
    { badge: 'PERMA',   name: 'Positive Emotion, Engagement, Relationships, Meaning, Achievement', desc: 'Wellbeing and motivation framework',
      text: 'Positive Emotion: [what creates positive feeling in this context? Joy, pride, gratitude, excitement?]\\n\\nEngagement: [what produces flow — deep focus without boredom or anxiety?]\\n\\nRelationships: [what strengthens connection, trust, and belonging?]\\n\\nMeaning: [what connects this to something bigger than the individual task?]\\n\\nAchievement: [what creates a sense of progress and accomplishment?]' },
    { badge: 'PEST',    name: 'Political, Economic, Social, Technological', desc: 'External environment analysis',
      text: 'Political: [government policy, regulation, political stability, trade restrictions, tax policy]\\n\\nEconomic: [growth rates, interest rates, inflation, disposable income, unemployment, exchange rates]\\n\\nSocial: [demographics, cultural attitudes, lifestyle trends, education, health consciousness]\\n\\nTechnological: [innovation, automation, R&D activity, technology incentives, barriers to entry]\\n\\nKey implications for [[subject]]: [top 3 factors that most affect your situation and why]' },
    { badge: 'TLDR',    name: 'Too Long Didnt Read — Summary Format',   desc: 'Instant summary structure',
      text: 'TL;DR: [one sentence — the single most important thing to know]\\n\\nThe context: [2 sentences — what is happening and why it matters]\\n\\nThe key points:\\n1. [most important]\\n2. [second most important]\\n3. [third most important]\\n\\nThe action: [what the reader should do with this information, if anything]' },
    { badge: 'Fishbone', name: 'Ishikawa Cause-and-Effect Diagram',     desc: 'Root cause analysis across 6 categories',
      text: 'Effect (problem to solve): [state the problem clearly]\\n\\nCauses by category:\\n\\nPeople: [human factors — skill gaps, errors, training]\\nProcess: [method or procedure failures]\\nMachinery/Tools: [equipment, software, or tooling issues]\\nMaterials: [input quality, data, or resource issues]\\nMeasurement: [metrics, feedback, or data quality issues]\\nEnvironment: [physical, cultural, or external context]\\n\\nMost likely root cause: [the cause with the most downstream effects]\\nPriority fix: [the highest-leverage intervention]' },
    { badge: 'OKR',     name: 'Objectives and Key Results',             desc: 'Goal-setting for teams and individuals',
      text: 'Objective: [an inspiring, qualitative statement of what you want to achieve — ambitious but not measured]\\n\\nKey Result 1: [specific, measurable outcome that would prove the objective was met]\\nBaseline: [current value] → Target: [goal value] by [date]\\n\\nKey Result 2: [another measurable outcome]\\nBaseline: [current value] → Target: [goal value] by [date]\\n\\nKey Result 3: [another measurable outcome]\\nBaseline: [current value] → Target: [goal value] by [date]\\n\\nCheck-in cadence: [weekly / bi-weekly / monthly]\\nOwner: [who is accountable for this OKR]' },"""

# ── 4. Apply insertions ────────────────────────────────────────────────────

# Insert new blocks just before `\n  ];\n\n  var FRAMEWORKS`
BLOCKS_ANCHOR = '\n  ];\n\n  var FRAMEWORKS = ['
assert BLOCKS_ANCHOR in code, "BLOCKS_ANCHOR not found"
code = code.replace(BLOCKS_ANCHOR, NEW_BLOCKS + BLOCKS_ANCHOR, 1)

# Insert new frameworks just before `\n  ];\n\n  var _canvasBlocks`
FRAMEWORKS_ANCHOR = '\n  ];\n\n  var _canvasBlocks'
assert FRAMEWORKS_ANCHOR in code, "FRAMEWORKS_ANCHOR not found"
code = code.replace(FRAMEWORKS_ANCHOR, NEW_FRAMEWORKS + FRAMEWORKS_ANCHOR, 1)

open('static/app.js', 'w', encoding='utf-8').write(code)

# Count results
import re
pcw_idx = code.index('(function initComponentsWorkspace()')
# Find IIFE end
depth=0; pos=pcw_idx; found=-1
while pos < len(code) and found == -1:
    if code[pos] == '(': depth += 1
    elif code[pos] == ')':
        depth -= 1
        if depth == 0 and pos > pcw_idx + 10: found = pos
    pos += 1
section = code[pcw_idx:found+2]

block_count = len(re.findall(r"cat: '(\w+)'", section))
fw_count = len(re.findall(r"badge: '", section))
cat_ids = re.findall(r"id: '(\w+)'", section[:section.index('var BLOCKS')])
print('Blocks:', block_count)
print('Frameworks:', fw_count)
print('Categories:', cat_ids)
print('Done.')
